/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FloatingNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var runtimeRequire = typeof require === "function" ? require : null;
var LEGACY_DEFAULT_SETTINGS = {
  noteFolder: "Call Notes",
  noteTitleFormat: "Call - YYYY-MM-DD HH[h]mm",
  defaultNoteContent: "# \u{1F4DE} Call Notes\n\n**Date:** {{date}}\n\n---\n\n"
};
var DEFAULT_SETTINGS = {
  noteFolder: "Quick Notes",
  noteTitleFormat: "[Quick] - YYYY-MM-DD HH[h]mm",
  windowWidth: 480,
  windowHeight: 600,
  defaultNoteContent: "# Quick Notes\n\n**Date:** {{date}}\n\n---\n\n",
  alwaysOnTop: true,
  opacity: 100
};
var FloatingNotePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "open-new-note",
      name: "Open new note",
      callback: () => this.openFloatingNote(true)
    });
    this.addCommand({
      id: "open-todays-note",
      name: "Open today's quick note (floating)",
      callback: () => this.openFloatingNote(false)
    });
    this.addRibbonIcon("pin", "Open new floating quick note", () => {
      void this.openFloatingNote(true);
    });
    this.addSettingTab(new FloatingNoteSettingTab(this.app, this));
  }
  async openFloatingNote(createNew) {
    const file = createNew ? await this.createNewQuickNote() : await this.getOrCreateTodaysQuickNote();
    if (!file) {
      new import_obsidian.Notice("Failed to create or find a quick note.");
      return;
    }
    const leaf = this.app.workspace.openPopoutLeaf({
      size: {
        width: this.settings.windowWidth,
        height: this.settings.windowHeight
      }
    });
    await leaf.openFile(file, { active: true });
    setTimeout(() => {
      this.lightenPopoutHeaderBar(leaf);
      this.applyWindowSettings();
    }, 200);
  }
  lightenPopoutHeaderBar(leaf) {
    var _a, _b;
    const popoutDoc = (_b = (_a = leaf.view) == null ? void 0 : _a.containerEl) == null ? void 0 : _b.ownerDocument;
    if (!popoutDoc)
      return;
    const root = popoutDoc.documentElement;
    root.setCssProps({
      "--titlebar-background": "var(--background-secondary-alt)",
      "--titlebar-background-focused": "var(--background-secondary-alt)"
    });
  }
  applyWindowSettings() {
    var _a, _b, _c;
    try {
      const electronModule = runtimeRequire == null ? void 0 : runtimeRequire("electron");
      const win = (_b = (_a = electronModule == null ? void 0 : electronModule.remote) == null ? void 0 : _a.BrowserWindow.getFocusedWindow()) != null ? _b : null;
      if (win) {
        if (this.settings.alwaysOnTop) {
          win.setAlwaysOnTop(true, "floating");
          win.setVisibleOnAllWorkspaces(true);
        }
        if (this.settings.opacity < 100) {
          win.setOpacity(this.settings.opacity / 100);
        }
        (_c = win.setTitle) == null ? void 0 : _c.call(win, "Quick notes");
      } else {
        this.tryElectronRemote();
      }
    } catch (e) {
      this.tryElectronRemote();
    }
  }
  tryElectronRemote() {
    var _a, _b, _c, _d;
    try {
      if (!runtimeRequire) {
        throw new Error("Runtime require is not available.");
      }
      const electronRemote = runtimeRequire("@electron/remote");
      const browserWindow = (_c = (_b = electronRemote.BrowserWindow) != null ? _b : (_a = electronRemote.default) == null ? void 0 : _a.BrowserWindow) != null ? _c : null;
      const win = (_d = browserWindow == null ? void 0 : browserWindow.getFocusedWindow()) != null ? _d : null;
      if (win) {
        if (this.settings.alwaysOnTop) {
          win.setAlwaysOnTop(true, "floating");
          win.setVisibleOnAllWorkspaces(true);
        }
        if (this.settings.opacity < 100) {
          win.setOpacity(this.settings.opacity / 100);
        }
      }
    } catch (err) {
      new import_obsidian.Notice(
        "Could not set always on top. Your Obsidian version may not support this.",
        5e3
      );
      console.error("FloatingNote: Electron remote error", err);
    }
  }
  async createNewQuickNote() {
    const folder = this.settings.noteFolder;
    const title = (0, import_obsidian.moment)().format(this.settings.noteTitleFormat);
    const content = this.settings.defaultNoteContent.replace(
      "{{date}}",
      (0, import_obsidian.moment)().format("YYYY-MM-DD HH:mm")
    );
    await this.ensureFolderExists(folder);
    const MAX_ATTEMPTS = 100;
    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      const suffix = attempt === 1 ? "" : ` (${attempt})`;
      const candidate = folder ? `${folder}/${title}${suffix}.md` : `${title}${suffix}.md`;
      try {
        return await this.app.vault.create(candidate, content);
      } catch (e) {
      }
    }
    new import_obsidian.Notice("Could not create a unique note file after several attempts.");
    return null;
  }
  async getOrCreateTodaysQuickNote() {
    const folder = this.settings.noteFolder;
    const title = (0, import_obsidian.moment)().format("YYYY-MM-DD") + " Quick Notes";
    const path = folder ? `${folder}/${title}.md` : `${title}.md`;
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian.TFile) {
      return existing;
    }
    const content = this.settings.defaultNoteContent.replace(
      "{{date}}",
      (0, import_obsidian.moment)().format("YYYY-MM-DD")
    );
    await this.ensureFolderExists(folder);
    return await this.app.vault.create(path, content);
  }
  async ensureFolderExists(folder) {
    if (!folder)
      return;
    const existing = this.app.vault.getAbstractFileByPath(folder);
    if (!existing) {
      await this.app.vault.createFolder(folder);
    }
  }
  async loadSettings() {
    const savedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, savedData);
    let migrated = false;
    if (this.settings.noteFolder === LEGACY_DEFAULT_SETTINGS.noteFolder) {
      this.settings.noteFolder = DEFAULT_SETTINGS.noteFolder;
      migrated = true;
    }
    if (this.settings.noteTitleFormat === LEGACY_DEFAULT_SETTINGS.noteTitleFormat) {
      this.settings.noteTitleFormat = DEFAULT_SETTINGS.noteTitleFormat;
      migrated = true;
    }
    if (this.settings.noteTitleFormat === "Quick - YYYY-MM-DD HH[h]mm") {
      this.settings.noteTitleFormat = DEFAULT_SETTINGS.noteTitleFormat;
      migrated = true;
    }
    if (this.settings.noteTitleFormat === "Note") {
      this.settings.noteTitleFormat = "[Note]";
      migrated = true;
    }
    if (this.settings.defaultNoteContent === LEGACY_DEFAULT_SETTINGS.defaultNoteContent) {
      this.settings.defaultNoteContent = DEFAULT_SETTINGS.defaultNoteContent;
      migrated = true;
    }
    if (migrated) {
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var FloatingNoteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Note preferences").setHeading();
    new import_obsidian.Setting(containerEl).setName("Notes folder").setDesc("Folder where quick notes are saved. Leave blank for vault root.").addText(
      (text) => text.setPlaceholder("Quick notes").setValue(this.plugin.settings.noteFolder).onChange(async (value) => {
        this.plugin.settings.noteFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("New note title format").setDesc(
      "Moment.js date format for new notes opened via 'Open new note'. Wrap plain text in square brackets (e.g. [Note])."
    ).addText(
      (text) => text.setPlaceholder("[Quick] - YYYY-MM-DD HH[h]mm").setValue(this.plugin.settings.noteTitleFormat).onChange(async (value) => {
        this.plugin.settings.noteTitleFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default note content").setDesc("Template for new notes. Use {{date}} for the current date/time.").addTextArea(
      (text) => text.setValue(this.plugin.settings.defaultNoteContent).onChange(async (value) => {
        this.plugin.settings.defaultNoteContent = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Window").setHeading();
    new import_obsidian.Setting(containerEl).setName("Always on top").setDesc("Keep the floating note window above other windows.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.alwaysOnTop).onChange(async (value) => {
        this.plugin.settings.alwaysOnTop = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Window width (px)").addSlider(
      (slider) => slider.setLimits(300, 1200, 20).setValue(this.plugin.settings.windowWidth).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.windowWidth = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Window height (px)").addSlider(
      (slider) => slider.setLimits(200, 1e3, 20).setValue(this.plugin.settings.windowHeight).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.windowHeight = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Window opacity (%)").setDesc("Make the window slightly transparent (100 = fully opaque).").addSlider(
      (slider) => slider.setLimits(30, 100, 5).setValue(this.plugin.settings.opacity).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.opacity = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
